// Generated by https://quicktype.io
import { User } from './User';
export interface IChatroom {
    _id:       string;
    isGroup:   boolean;
    groupName: null;
    users:     User[];
    createdAt: string;
    updatedAt: string;
    isActive: boolean;
}

